<a href="https://colab.research.google.com/github/Adnan-shareef/Pytorch-Youtube/blob/main/colab_und.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
2+2

4

In [ ]:
import torch
import numpy as np


Python List

In [ ]:
list=[[1,2,3,4],[5,6,7,8]]
print(list)

[[1, 2, 3, 4], [5, 6, 7, 8]]


Numpy

In [ ]:
np1=np.random.rand(3,4)
print(np1)

[[0.54644654 0.90741511 0.97589044 0.19463491]
 [0.14276884 0.84423304 0.28742688 0.02402657]
 [0.56686699 0.17599083 0.58049819 0.94258466]]


In [ ]:
np1.dtype

dtype('float64')

In [ ]:
pt=torch.randn(3,3,4)
pt

tensor([[[-1.6361, -1.0958,  1.8503,  0.7965],
         [-0.9320, -0.9373,  1.0358, -0.0383],
         [-0.5879,  0.5437,  0.7888, -0.2729]],

        [[ 0.7211, -0.6939,  1.4423,  0.4210],
         [-0.3582, -1.9480,  1.1165,  0.1539],
         [ 0.1261,  0.3783, -0.7616,  0.0266]],

        [[-0.1526, -0.9272, -0.6984,  0.0156],
         [ 0.8364,  0.6845,  0.7767, -1.0231],
         [ 0.6209,  0.3061,  0.8098, -0.5538]]])

In [ ]:
nptotorch=torch.tensor(np1)
print(nptotorch)

tensor([[0.5464, 0.9074, 0.9759, 0.1946],
        [0.1428, 0.8442, 0.2874, 0.0240],
        [0.5669, 0.1760, 0.5805, 0.9426]], dtype=torch.float64)
